name: drylab
channels:
  - r
  - cyclus
  - anaconda
  - bioconda
  - defaults
  - conda-forge
dependencies:
  - _libgcc_mutex=0.1=main
  - _r-mutex=1.0.0=anacondar_1
  - asciitree=0.3.3=py_2
  - asn1crypto=0.24.0=py36_0
  - backcall=0.1.0=py36_0
  - backports=1.0=py_2
  - bcftools=1.9=ha228f0b_4
  - bedtools=2.28.0=hdf88d34_0
  - binutils_impl_linux-64=2.31.1=h6176602_1
  - binutils_linux-64=2.31.1=h6176602_7
  - biopython=1.73=py36h7b6447c_0
  - blas=1.1=openblas
  - blosc=1.16.3=hd408876_0
  - bokeh=1.2.0=py36_0
  - bwa=0.7.17=h84994c4_5
  - bwidget=1.9.11=1
  - bzip2=1.0.8=h7b6447c_0
  - busco=4.0.4
  - ca-certificates=2019.5.15=1
  - cairo=1.14.12=h8948797_3
  - certifi=2019.6.16=py36_1
  - cffi=1.12.3=py36h2e261b9_0
  - chardet=3.0.4=py36_1
  - click=7.0=py36_0
  - cloudpickle=1.2.1=py_0
  - conda=4.7.11=py36_0
  - conda-package-handling=1.3.11=py36_0
  - configparser=3.7.4=py36_0
  - cooler=0.8.5=py36h1341992_0
  - cryptography=2.7=py36h1ba5d50_0
  - curl=7.65.2=hbc83047_0
  - cycler=0.10.0=py36_0
  - cytoolz=0.10.0=py36h7b6447c_0
  - dask=2.1.0=py_0
  - dask-core=2.1.0=py_0
  - dbus=1.13.6=h746ee38_0
  - decorator=4.4.0=py36_1
  - dill=0.3.0=py36_0
  - distributed=2.1.0=py_0
  - eigen=3.3.7=hfd86e86_0
  - expat=2.2.6=he6710b0_0
  - fit_nbinom=1.1=py_0
  - fontconfig=2.13.0=h9420a91_0
  - freetype=2.9.1=h8a8886c_1
  - fribidi=1.0.5=h7b6447c_0
  - future=0.17.1=py36_0
  - gatk=3.8=py36_0
  - gcc_impl_linux-64=7.3.0=habb00fd_1
  - gcc_linux-64=7.3.0=h553295d_7
  - gfortran_impl_linux-64=7.3.0=hdf63c60_1
  - gfortran_linux-64=7.3.0=h553295d_7
  - gitdb2=2.0.5=py_0
  - gitpython=2.1.12=py_0
  - glib=2.56.2=hd408876_0
  - graphite2=1.3.13=h23475e2_0
  - gsl=2.2.1=blas_openblashddceaf2_6
  - gst-plugins-base=1.14.0=hbbd80ab_1
  - gstreamer=1.14.0=hb453b48_1
  - gxx_impl_linux-64=7.3.0=hdf63c60_1
  - gxx_linux-64=7.3.0=h553295d_7
  - h5py=2.9.0=py36h7918eee_0
  - harfbuzz=1.8.8=hffaf4a1_0
  - hdf5=1.10.4=hb1b8bf9_0
  - heapdict=1.0.0=py36_2
  - hic2cool=0.7.1=py_0
  - hicexplorer=3.1=py_0
  - hicmatrix=10=py_1
  - htslib=1.9=ha228f0b_7
  - icu=58.2=h9c2bf20_1
  - idna=2.8=py36_0
  - intel-openmp=2019.4=243
  - intervaltree=3.0.2=py_0
  - ipython=7.7.0=py36h39e3cac_0
  - ipython_genutils=0.2.0=py36_0
  - java-jdk=8.45.14=0
  - jedi=0.13.3=py36_0
  - jellyfish=2.2.10=h6bb024c_1
  - jemalloc=4.5.0=0
  - jinja2=2.10.1=py36_0
  - jpeg=9b=h024ee3a_2
  - kiwisolver=1.1.0=py36he6710b0_0
  - krb5=1.16.1=h173b8e3_7
  - krbalancing=0.0.5=py36h6bb024c_0
  - ldc=1.13.0=h02c9852_1
  - libarchive=3.3.3=h5d8350f_5
  - libblas=3.8.0=11_openblas
  - libcblas=3.8.0=11_openblas
  - libcurl=7.65.2=h20c2e04_0
  - libdeflate=1.0=h14c3975_1
  - libedit=3.1.20181209=hc058e9b_0
  - libffi=3.2.1=hd88cf55_4
  - libgcc=7.2.0=h69d50b8_2
  - libgcc-ng=8.2.0=hdf63c60_1
  - libgfortran-ng=7.3.0=hdf63c60_0
  - liblapack=3.8.0=11_openblas
  - libopenblas=0.3.6=h5a2b251_1
  - libpng=1.6.37=hbc83047_0
  - libssh2=1.8.2=h1ba5d50_0
  - libstdcxx-ng=8.2.0=hdf63c60_1
  - libtiff=4.0.10=h2733197_2
  - libuuid=1.0.3=h1bed415_2
  - libxcb=1.13=h1bed415_1
  - libxml2=2.9.9=hea5a465_1
  - locket=0.2.0=py36_1
  - lz4-c=1.8.1.2=h14c3975_0
  - lzo=2.10=h49e0be7_2
  - make=4.2.1=h1bed415_1
  - markupsafe=1.1.1=py36h7b6447c_0
  - mashmap=2.0=gsl2.2_1
  - matplotlib=3.0.3=py36h5429711_0
  - miniasm=0.3_r179=ha92aebf_0
  - minimap2=2.17=h84994c4_0
  - mkl=2019.4=243
  - mkl-service=2.0.2=py36h7b6447c_0
  - mock=3.0.5=py36_0
  - msgpack-python=0.6.1=py36hfd86e86_1
  - multiprocess=0.70.8=py36h516909a_0
  - mummer4=4.0.0beta2=pl526hf484d3e_4
  - ncurses=6.1=he6710b0_1
  - numexpr=2.6.9=py36h2ffa06c_0
  - numpy=1.17.0=py36h95a1406_0
  - olefile=0.46=py36_0
  - openblas=0.3.3=h9ac9557_1001
  - openjdk=8.0.152=h46b5887_1
  - openssl
  - packaging=19.0=py36_0
  - pairix=0.3.7=py36h84994c4_0
  - pandas=0.24.2=py36he6710b0_0
  - pango=1.42.4=h049681c_0
  - parso=0.5.0=py_0
  - partd=1.0.0=py_0
  - pcre=8.43=he6710b0_0
  - perl=5.26.2=h14c3975_0
  - pexpect=4.7.0=py36_0
  - picard=2.20.4=0
  - pickleshare=0.7.5=py36_0
  - pillow=6.1.0=py36h34e0f95_0
  - pip=19.1.1=py36_0
  - pixman=0.38.0=h7b6447c_0
  - prompt_toolkit=2.0.9=py36_0
  - psutil=5.6.3=py36h7b6447c_0
  - ptyprocess=0.6.0=py36_0
  - pybigwig=0.3.16=py36h5295baf_0
  - pybind11=2.2.4=py36hfd86e86_0
  - pycosat=0.6.3=py36h14c3975_0
  - pycparser=2.19=py36_0
  - pyfaidx=0.5.5.2=py_1
  - pygenometracks=3.0=py_0
  - pygments=2.4.2=py_0
  - pyopenssl=19.0.0=py36_0
  - pyparsing=2.4.0=py_0
  - pyqt=5.9.2=py36h05f1152_2
  - pysam=0.15.2=py36h4b7d16d_3
  - pysamstats=1.1.2=py36h84994c4_4
  - pysocks=1.7.0=py36_0
  - pytables=3.5.2=py36h71ec239_1
  - python=3.6.8=h0371630_0
  - python-dateutil=2.8.0=py36_0
  - python-libarchive-c=2.8=py36_11
  - pytz=2019.1=py_0
  - pyyaml=5.1=py36h7b6447c_0
  - qt=5.9.7=h5867ecd_1
  - quast=5.0.2
  - r=3.6.0=r36_0
  - r-base=3.6.0=hce969dd_0
  - r-boot=1.3_20=r36h6115d3f_0
  - r-class=7.3_15=r36h96ca727_0
  - r-cluster=2.0.8=r36ha65eedd_0
  - r-codetools=0.2_16=r36h6115d3f_0
  - r-foreign=0.8_71=r36h96ca727_0
  - r-kernsmooth=2.23_15=r36ha65eedd_4
  - r-lattice=0.20_38=r36h96ca727_0
  - r-mass=7.3_51.3=r36h96ca727_0
  - r-matrix=1.2_17=r36h96ca727_0
  - r-mgcv=1.8_28=r36h96ca727_0
  - r-nlme=3.1_139=r36ha65eedd_0
  - r-nnet=7.3_12=r36h96ca727_0
  - r-recommended=3.6.0=r36_0
  - r-rpart=4.1_15=r36h96ca727_0
  - r-spatial=7.3_11=r36h96ca727_4
  - r-survival=2.44_1.1=r36h96ca727_0
  - readline=7.0=h7b6447c_5
  - requests=2.22.0=py36_0
  - ruamel_yaml=0.15.46=py36h14c3975_0
  - sambamba=0.7.0=h89e63da_0
  - samblaster=0.1.24=h6bb024c_2
  - samtools=1.9=h8571acd_11
  - scipy=1.2.1=py36_blas_openblash1522bff_0
  - setuptools=41.0.1=py36_0
  - sip=4.19.8=py36hf484d3e_0
  - six=1.12.0=py36_0
  - smmap2=2.0.5=py_0
  - snappy=1.1.7=hbae5bb6_3
  - sortedcontainers=2.1.0=py36_0
  - sqlite=3.27.2=h7b6447c_0
  - tabulate=0.8.3=py_0
  - tblib=1.4.0=py_0
  - tk=8.6.8=hbc83047_0
  - tktable=2.10=h14c3975_0
  - toolz=0.10.0=py_0
  - tornado=6.0.3=py36h7b6447c_0
  - tqdm=4.7.2=py36_0
  - traitlets=4.3.2=py36_0
  - unidecode=1.0.23=py36_0
  - urllib3=1.24.2=py36_0
  - wcwidth=0.1.7=py36_0
  - wheel=0.33.4=py36_0
  - xz=5.2.4=h14c3975_4
  - yaml=0.1.7=had09818_2
  - zict=1.0.0=py_0
  - zlib=1.2.11=h7b6447c_3
  - zstd=1.3.7=h0b5b093_0
  - awscli=1.16.218
  - preseq
  - ucsc-bedgraphtobigwig
  - scikit-learn
  - whatshap
  - tabix
  - hapcut2
  - freebayes
  - parallel
  - wtdbg
  - dataclasses
  - scikit-image
  - seqkit
  - deeptools
  - pip:
    - boto3
    - argh==0.26.2
    - blinker==1.4
    - clodius==0.10.13
    - cosmos-wfm==2.8.20
    - drmaa==0.7.9
    - flask==1.1.1
    - funcsigs==1.0.2
    - itsdangerous==1.1.0
    - more-itertools==7.2.0
    - negspy==0.2.22
    - networkx==2.3
    - nose==1.3.7
    - regex==2016.06.24
    - slugid==2.0.0
    - sqlalchemy==1.3.6
    - werkzeug==0.15.5
    - hic-straw==0.0.6
    - peakachu
    - mgzip
    - PyGithub
    - opencv-contrib-python 
prefix: /home/jay/miniconda3_latest
